name: Upload Sandra's Work Schedule to Google Calendar

on:
  schedule:
    # Runs at 00:00, on day 1 of the month
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  ping-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Vercel Endpoint
        env:
          CRON_URL: ${{ secrets.VERCEL_CRON_URL_UPLOAD_WORK_SCHEDULE }}
          CRON_SECRET: ${{ secrets.VERCEL_CRON_SECRET }}
        run: |
          curl -v -L -X GET "$CRON_URL" \
          -H "Authorization: Bearer $CRON_SECRET" 
