name: Upload Sandra's Work Schedule to Google Calendar

on:
  schedule:
    # Runs at 00:00, on day 1 of the month
    - cron: '0 0 1 * *'

jobs:
  ping-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Vercel Endpoint
        run: |
          curl -X GET "${{secrets.VERCEL_CRON_URL_UPLOAD_WORK_SCHEDULE}} \
          -H Authorization: Bearer ${{ secrets.VERCEL_CRON_SECRET }}"
